apiVersion: v1
kind: ConfigMap
metadata:
  name: maintenance-config
  namespace: "maintenance"
data:
  default.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      location / {
        return 503;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /etc/nginx/conf.d;
      }
    }
  50x.html: |
    <!doctype html>
    <title>{{ .Values.platformName }}</title>
    <style>
    body { text-align: center; padding: 150px; }
    h1 { font-size: 50px; }
    body { font: 20px Helvetica, sans-serif; color: #333; }
    article { display: block; text-align: left; width: 650px; margin: 0 auto; }
    a { color: rgb(135, 10, 48); text-decoration: none; }
    a:hover { color: #333; text-decoration: none; }
    </style><article>
    <h1>We&rsquo;ll be back soon!</h1>
    <div>
    <p>Sorry for the inconvenience but we&rsquo;re performing some maintenance at the moment. If you need to you can always <a href="mailto:{{ .Values.contactEmail }}">contact us</a>, otherwise we&rsquo;ll be back online shortly!</p>
    <p>&mdash; The {{ .Values.platformName }} Team</p>
    </div>
    </article>