{{ if .Values.svcMongoDb.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.svcMongoDb.pvClaimName }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ tpl .Values.svcMongoDb.storageClass $ }}
  accessModes: {{ .Values.svcMongoDb.accessModes }}
  {{- if .Values.svcMongoDb.volumeName }}
  volumeName: {{ .Values.svcMongoDb.volumeName }}
  {{- end}}
  resources:
    requests:
      storage: {{ .Values.svcMongoDb.storageRequested }}
{{ end }}