{{ if .Values.svcMongoDb.enabled }}
{{ if eq (default .Values.svcMongoDb.storageClass "") "influenzanet-storage" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "influenzanet-storage"
  namespace: {{ .Values.namespace }}
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
{{ end }}
{{ end }}